# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  #- jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Moorpark College Journalism
subtitle: ""
email:
name:
description: >
  A showcase of Moorpark College student journalism.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/mcjournalism" # the subpath of your site, e.g. /blog/
url: "https://seangreene.github.io" # the base hostname & protocol for your site
cover: "/assets/banner.jpg"
logo: "/assets/MCJlogo-blue.jpg"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"


collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"    
# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives:
#  enabled:
#    - categories
#    - tags
#  layout: 'archive'
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
#descriptions:
#  - cat: jekyll
#    desc: "Posts describing Jekyll setup techniques."
#
#  - cat: dummy
#    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
social:
  - name: Twitter                         # Name of the service
    icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
    username: "@MCJournalismNow"             # (User) Name to display in the footer link
    url: https://twitter.com/MCJournalismNow # URL of your profile (leave blank to not display in footer)
    desc: Follow us on Twitter            # Description to display as link title, etc
    share: true                           # Include in the "Share" section of posts

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: ""
    fb_image_width: 1173
    fb_image_height: 880
    fb_image_type: "image/jpg"

    twitter_image: ""

    os_repo: "https://github.com/seangreene/mcjournalism.com"
    os_rcs_type: "git"
    os_src: "git@github.com:seangreene/mcjournalism.git"
